hash-format = "sha256"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5c477b0cd218ed14c178205ad498aa7f3eb1ec56444c2e760e0413e8d520c064"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "26a6c62dd5e1b6812ffdf82fa05d64513100661704a3b247e7e88f10a8143923"
metafile = true

[[files]]
file = "mods/sky++.pw.toml"
hash = "bc137ce43247c4f3477d355ba01dfaa71865ce102b08c73b5718bac8d199216f"
metafile = true
