name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93dfaf66962e461dc2f86642ac7f2e8a4d2139760bbe6b9628c28d63df10e7f5"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
