name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c9eccfa470dd4f7c108ddebc2c0f7aad8226e86513e3733160e5504558fdf68"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
