name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40084699196bbc2760e08f85f8e8630f39f11dfd3c44a9ac4277f807d4072fd1"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
