name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97eecef6819908e37e7b17f9e95426118d2b5e91b8b4f5222844cd5d971cb320"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
