name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39763b63ef8cedef55bcc3bdd953ff96073c2743b3e6704637b039a0bda29e8b"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
