name = "Skyblock Netcessities"
author = "AnotherPillow"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69e2491f95fec04cee752ab74510236b691755336b77e2bbfae62276ec2af406"

[versions]
minecraft = "1.19.2"
quilt = "0.29.3-beta.1"
